### ISSUE TITLE
Page attributes

### ISSUE THREAD

**Issue by SankarSrinivasan1** [themeum/qubely#1]
Qubely should add "Qubely Template" in ""Page Attributes"". It is useful to select the template when creating new page. Site title and tagline and footer lines should be suppressed when selecting Qubely template.

**Comment by anik4e** [comment]
Thank you so much for concern. Actually we miss this. We add this as soon as possible.

**Comment by SankarSrinivasan1** [comment]
Thank you Anik

**Comment by anik4e** [comment]
Page Template Added in **Page_Template** branch, We need some check and after checking hopefully we will release this in next version.

[Page Template](https://github.com/themeum/qubely/tree/Page_Template)

**Comment by SankarSrinivasan1** [comment]
Wow... Thank you so much :+1:

**Comment by SankarSrinivasan1** [comment]
Dear Anik

This is different kind of issue. After importing and designing a block, it is looking pretty in the front end. But, after saving the page it is looking text only. Not all times, but some times it is looking like this. Find the attachment. Thank you

![1](https://user-images.githubusercontent.com/53850760/63738845-c4016f00-c8a8-11e9-8f57-f08c1f6336d3.png)
![2](https://user-images.githubusercontent.com/53850760/63738847-c4016f00-c8a8-11e9-8c3d-9f6e8ddd253c.png)

**Comment by anik4e** [comment]
Yes, Our QA already noticed it. :)

**Comment by SankarSrinivasan1** [comment]
Ok. Thank you

**Comment by anik4e** [comment]
Page template released with V.1.1.3

**Comment by SankarSrinivasan1** [comment]
Thanks Anil... I got email newsletter regarding this. Thanks a lot. Building a LMS theme with help of Qubely and Tutor. Thanks...

**Comment by anik4e** [comment]
Our next theme is on a progress with Qubely and Tutor named "UpSkill". We already have a theme with Qubely and Tutor.

Please take a look-
https://www.themeum.com/product/docent-pro/

**Comment by SankarSrinivasan1** [comment]
Mr. Anik... Already I have withdrawn my effort. Thank you for reply, even after 2 months.

**Comment by anik4e** [comment]
Okay
