### ISSUE TITLE
Filter to unset blocks

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#10]
I don't want my client to pick all available blocks. Thats to much. Please provide a filter to unset certain blocks from your collection.

**Comment by anik4e** [comment]
@nicmare its a Gutenberg default feature. You can deactivate any block from **Block Manager** 

Here is the screenshot-
http://prntscr.com/pu2310

If you have any more confusion let me know.

**Comment by nicmare** [comment]
cool. did not know that. thank you @anik4e

**Comment by anik4e** [comment]
@nicmare Thank You So Much
