### ISSUE TITLE
More (custom) Breakpoints?

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#12]
at the moment one can choose between three breakpoints in block settings. but i really need more. please provide a filter for breakpoint threshold and for more breakpoints. something like this:
```
$grid-breakpoints = array (
        "xs" => array("icon"=>"mobile",threshold=>0),
        "sm" => array("icon"=>"mobile2",threshold=>"360px"),
        "md" => array("icon"=>"tablet",threshold=>"576px"),
        "lg" => array("icon"=>"tablet2",threshold=>"768px"),
        "xl" => array("icon"=>"desktop",threshold=>"992px"),
        "xxl" => array("icon"=>"desktop2",threshold=>"1260px"),
);
```

**Comment by anik4e** [comment]
@nicmare when we started qubely from scratch, it has 6 breakpoint. But after starting we will realize that it should be more complex to the end user to edit. That's why we use only three break point. I am not sure is it our good decision or bad. What do you think from the end user position?

**Comment by nicmare** [comment]
sure. 3 breakpoints by default is good! but on some projects i need more. therefore filter on code level would be neat.

**Comment by anik4e** [comment]
Ok i will discuss this issue with our RND team again. Thanks
