### ISSUE TITLE
Additional CSS not working on container boxes

### ISSUE THREAD

**Issue by ntrpy** [themeum/qubely#13]
First off: qubely is awesome, thanks for sharing!

One bug I noticed: when you try to insert additional CSS with the {{QUBELY}}-prefix in the row and column blocks, it gets ignored and will not be persisted during page save.
On other blocks, this works just fine, I tried it with the Advanced-Text and Info-Box blocks.

**Comment by anik4e** [comment]
Hello @ntrpy ,
It's a Row and Column bug. I fixed this issue in high priority. It will attached in Monday update (Version 1.2.2)
https://github.com/themeum/qubely/commit/93a76cba15126a5b5862b9ae72fcabc2614cc925

Working Screenshot
http://prntscr.com/pu7gul

If you feel free then give us a five star in WordPress directory. 😊 
https://wordpress.org/plugins/qubely/
Thank you so much.
