### ISSUE TITLE
wp-block-qubely-image uses full size images

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#14]
i've noticed that you can choose between S M L and Custom in Image Block Settings. But qubely always takes the same image *file* but just sets pixel dimensions on it. would love to see the real image sizes from "image_size_names_choose" wp filter. in this filter i find all images defined by "add_image_size" function. so i can also choose for instance a thumbnail image which has real size of 150x150 pixel. this would save a lot of traffic…

**Comment by nicmare** [comment]
same for wp-block-qubely-team image. always loads full size image

**Comment by nicmare** [comment]
in qubely-postgrid-wrapper you can choose the real image size. good!

**Comment by nicmare** [comment]
same with wp-block-qubely-teamcarousel

**Comment by nicmare** [comment]
same with wp-block-qubely-gallery thumbnails

**Comment by jakirhasan** [comment]
Hi @nicmare,

Thank you so much for your opinion. We have used add_image_size only for posts. You can insert any image size for others blocks. I mean, You can upload exact image size to ignore loading issue.

Have a nice day...

**Comment by g-man-jones** [comment]
Yes, this should not be closed, perhaps moved to a feature request.

It's a basic expectation that the image block should support selecting from the theme thumbnail sizes...
