### ISSUE TITLE
wrong date format in qubely-postgrid-wrapper frontend

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#15]
wp setting:
<img width="477" alt="Screenshot 2019-11-08 14 40 45" src="https://user-images.githubusercontent.com/898582/68480758-da775f80-0235-11ea-8220-50de7a42d1ff.png">
qubely backend:
<img width="406" alt="Screenshot 2019-11-08 14 40 41" src="https://user-images.githubusercontent.com/898582/68480779-e2370400-0235-11ea-9f6e-5bdef10eae76.png">
qubely frontend:
<img width="437" alt="Screenshot 2019-11-08 14 40 51" src="https://user-images.githubusercontent.com/898582/68480787-e7944e80-0235-11ea-82f4-f8e2da34f477.png">

**Comment by themeum** [comment]
We have fixed date issue. Please use latest version

Thanks
