### ISSUE TITLE
wp-block-qubely-pricelist wrong color in media digit

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#16]
Qubely Backend (good):
<img width="788" alt="Screenshot 2019-11-08 14 52 22" src="https://user-images.githubusercontent.com/898582/68481420-6fc72380-0237-11ea-893d-91d05a15b3a8.png">

Qubely Frontend:
<img width="528" alt="Screenshot 2019-11-08 14 53 06" src="https://user-images.githubusercontent.com/898582/68481439-7b1a4f00-0237-11ea-9152-96824c8f496f.png">

Media Digit Text-Color is wrong. gets the color from discount price color instead of white!

**Comment by anik4e** [comment]
Working Great in Setup-

Backend-
http://prntscr.com/pv7uh8

Frontend-
http://prntscr.com/pv7upo

Clear your browser cache then check.
