### ISSUE TITLE
Timeline Date needs media query for position attribute

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#19]
problem with spacing value of 0 on small devices:
<img width="482" alt="Bildschirmfoto 2019-11-11 um 14 31 39" src="https://user-images.githubusercontent.com/898582/68590967-ff670f00-048f-11ea-9eec-5d60a141b80f.png">
solution:
```
.qubely-block-timeline .qubely-timeline-date-container {
        position: static;
        @media screen and (min-width: 768px) {
            position: absolute;
        }
    }
```
accept position:absolute when reaching breakpoint

**Comment by themeum** [comment]
Hi @nicmare,

We already fixed this issue. Soon we will release update.
Have a nice day...

Thanks
