### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by SankarSrinivasan1** [themeum/qubely#2]
A spelling mistake in Video Popup Block. Please find attachment.

![qubely](https://user-images.githubusercontent.com/53850760/66194523-418f7a80-e6b2-11e9-8513-997f22ac26f5.png)

**Comment by murshed** [comment]
Thanks so much. We'll fix an upcoming version.

**Comment by SankarSrinivasan1** [comment]
Thank you

**Comment by themeum** [comment]
We already fix video popup spelling issue. Please update latest version.

**Comment by SankarSrinivasan1** [comment]
Thank you Fahim. I will update.
