### ISSUE TITLE
Feature Request: Responsive Height with padding-top

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#20]
Can we have it please like bootstrap:
https://www.w3schools.com/bootstrap4/tryit.asp?filename=trybs_util_embeds

At the moment you have to define a fixed height. Its always the same height on small devices and large screens. For instance in Video Popup. Instead of selecting the height, more options to choose from aspect ratios would be better: square, 4:3, 16:9, 21:9 – then it would be truly responsive

**Comment by anik4e** [comment]
We check your problem. You can control your size using fixed height(With Responsive Settings).
But this is not be possible to add ratio. i already talk with this issue with top developer.
Thank you so much.
