### ISSUE TITLE
Global Colors missing in text-color option?!

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#21]
Where is it?
<img width="445" alt="Bildschirmfoto 2019-11-11 um 15 26 51" src="https://user-images.githubusercontent.com/898582/68594401-bf0b8f00-0497-11ea-8d8a-1396dc3e42b6.png">

**Comment by anik4e** [comment]
Fixed this issue. In next update you will find this option.
https://github.com/themeum/qubely/commit/3a8b87334043f3299e56446647fb88e893cc5150
