### ISSUE TITLE
Can't change color of devider dot

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#23]
The dot always remains black:
<img width="685" alt="Bildschirmfoto 2019-11-12 um 18 38 51" src="https://user-images.githubusercontent.com/898582/68695649-b8564800-057b-11ea-8e6c-9c49c3d13393.png">

**Comment by anik4e** [comment]
Thanks for bug report. We fixed the bug. In next update we will add this. 
https://github.com/themeum/qubely/commit/1676ab28ec5dda3482d83ee4b09ce1f379180909
Thanks.
