### ISSUE TITLE
Team Carousel: missing alignment for images

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#25]
in this configuration i miss the center alignment for user images. therefore it is left aligned but text is centered:
<img width="1210" alt="Bildschirmfoto 2019-11-14 um 14 05 18" src="https://user-images.githubusercontent.com/898582/68859599-eb1d4f00-06e7-11ea-8fb3-f6c82ca8c7ae.png">

**Comment by jakirhasan** [comment]
Hi @nicmare,
Thank you so much for this bug report. I already fixed this issue. Soon we will release update. 

Have a nice day...
