### ISSUE TITLE
Qubely image blurb freezes

### ISSUE THREAD

**Issue by munayam** [themeum/qubely#26]
While changing the image text from qubely image blurb everything freezes

**Comment by anik4e** [comment]
Actually if you give us more details about this that should be easier to fix the issue. Can you please give me a screenshot?

**Comment by anik4e** [comment]
Hey i got the issue & it has been fixed. From the next version 1.2.5 it will be live.
https://github.com/themeum/qubely/commit/766b0d431ae9c3c0a60d0bdf4272a75bd85ca103

Thanks @munayam for creating issue.
