### ISSUE TITLE
Qubely Image - Blurb - No url option

### ISSUE THREAD

**Issue by jgarib** [themeum/qubely#29]
In the Qubely image block there is an option for a URL in the "Simple" layout, but not int he "Blurb" layout. It would be handy to have this available in the "Blurb" layout as well for situations where you want to use an image as a navigation element and need the text to provide context.

**Comment by themeum** [comment]
Hello

Thank you for your query. I will pass it to my team. They will work on it
soon. This feature was requested before i hope they will work on it soon.
Till then i hope to have your patience.

Thank you
Best regards



How would you rate my reply?
Great
<https://secure.helpscout.net/satisfaction/317301479/record/3097860176/1/>
   Okay
<https://secure.helpscout.net/satisfaction/317301479/record/3097860176/2/>
   Not Good
<https://secure.helpscout.net/satisfaction/317301479/record/3097860176/3/>

--
Gianna Clark
Support Engineer
{#HS:1092317385-20062#}
