### ISSUE TITLE
Error in Tab Block

### ISSUE THREAD

**Issue by SankarSrinivasan1** [themeum/qubely#3]
If I download readymade Tab block through "Import Layout" - "Bundles" - "Corporate", that is not displaying correctly. Please find attachments.
![qube1](https://user-images.githubusercontent.com/53850760/66282212-19835f80-e8dc-11e9-8b63-289c63723065.png)
![qube2](https://user-images.githubusercontent.com/53850760/66282214-1a1bf600-e8dc-11e9-9fb6-c6390b54d8c0.png)

**Comment by murshed** [comment]
Hi,
Thanks again for posting this issue.

I have checked this and I never face on my localhost.

Video: https://streamable.com/uq0jr

Can you please check this issue after changing the current theme to "Twenty Nineteen" theme?

Regards.

**Comment by SankarSrinivasan1** [comment]
Hi Murshed

I request you, please don't stuck with localhost and twenty nineteen. It can be working well in both. 

I am building new theme on Underscores with Qubely and without any other plugins. Browser cache is not a issue. I think some issues in CSS part of Qubely, and it may raise a conflict. Thank you

**Comment by murshed** [comment]
Sure, I'll let you know after checking with the Underscores theme.
Can you please show us your dev live site URL also, page console screenshot?

**Comment by SankarSrinivasan1** [comment]
Hi Fahim

I have posted screenshot in my first message above. 

I will share URL with you once I complete the theme. Please allow me few days. Actually you should sponsor my theme 😄

**Comment by SankarSrinivasan1** [comment]
Hi Fahim

Please share your email address

**Comment by murshed** [comment]
Please email us support@themeum.com

**Comment by SankarSrinivasan1** [comment]
Hi Fahim, I have mailed you with my development site URL

**Comment by murshed** [comment]
Hi,
Thanks for your email.
I have shared your site URL with our team.
I think you need to finish your theme development then I can check and review.

All the best.

**Comment by SankarSrinivasan1** [comment]
Thank you Fahim... I will let you know once I complete the theme...
