### ISSUE TITLE
Free version: “add block” panel closes unexpectedly while hovering over some block icons

### ISSUE THREAD

**Issue by rmego** [themeum/qubely#44]
This happens while hovering over the following block icons:
- Accordion,
- Button group,
- Icon list.

![2020-10-12 22 13 14](https://user-images.githubusercontent.com/28367666/95804194-585ea900-0cd8-11eb-84a8-98e7935ad349.gif)

Fresh WordPress 5.5.1 installation on a Nginx server, no plugins installed, default theme activated (Twenty Twenty).

**Comment by rmego** [comment]
This has been reported before on [WordPress.org support channel](https://wordpress.org/support/topic/problems-with-the-blocks-when-you-hover-your-mouse/).

**Comment by fai-sal** [comment]
This issue is already resolved. Thank you
