### ISSUE TITLE
Post Grid issue

### ISSUE THREAD

**Issue by SankarSrinivasan1** [themeum/qubely#5]
Regarding "Post Grid" block, if I choose 3 posts to display, it is working well. But no option to move further. (Next / Previous).

- It is necessary to make a user to see next posts and previous posts. 

- "Single post page layout" also a good choice in addition to "Qubely Canvas"

**Comment by murshed** [comment]
Sankar,
We don't have that feature at this time.
We'll add an upcoming version.
