### ISSUE TITLE
Row Block

### ISSUE THREAD

**Issue by SankarSrinivasan1** [themeum/qubely#6]
Dear Team, in ROW block there are options for background. If I choose background image, it is better to add an option to enter URL of background image. Sorry for my annoying repeated requests to add the features.

![qubely row](https://user-images.githubusercontent.com/53850760/67916149-c9d24400-fbba-11e9-9e94-7f75b582f01b.png)

**Comment by anik4e** [comment]
I talk about this feature with our RND team. After confirmation i will add this in core. Thanks.
