### ISSUE TITLE
Error on WP 6.6 version

### ISSUE THREAD

**Issue by everaldomatias** [themeum/qubely#91]
When updating WP to version 6.6, Qubely blocks stopped working with the message "Your site doesn't include support for the "qubely/row". You can leave block intact, convert to a Custom HTML block, or remove if entirely ."

**Comment by aumkub** [comment]
They're still no update on Sep 2024 T T OMG

**Comment by sifat009** [comment]
This PR #92 should fix the issue.

**Comment by Shad0vv** [comment]
Please tell me where I can download version 1.8.12, several of my sites are made on this platform! Thank you!

**Comment by sifat009** [comment]
This issue is fixed in `version-1.8.12`
